#!/usr/bin/env node
const request = require('superagent');
const data = {1: 0, 2: 0};

async function get() {
    return new Promise((resove)=>{
        request.get('http://localhost:8080/')
        .end((error, res) => {
            const { msg, server } = res.body;
            console.log(msg);
            data[server]++;
            resove();
        });
    });
}

async function main() {
    for (let i = 0; i < 20; i++) {
        await get();
    }
    console.log(data);
}

main();
